# Generated by Django 5.1 on 2024-08-21 16:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Juan Luna', max_length=75)),
                ('address', models.CharField(choices=[(1, 'Zone 1'), (2, 'Zone 2'), (3, 'Zone 3'), (4, 'Zone 4'), (5, 'Zone 5'), (6, 'Zone 6'), (7, 'Zone 7'), (8, 'Zone 8')], default=1, max_length=55)),
                ('family_size', models.PositiveIntegerField(default=1)),
                ('priority', models.BooleanField(default=False)),
                ('assigned', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Residents',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Room 101', max_length=75)),
                ('building', models.CharField(default='Tower of God', max_length=80)),
                ('capacity', models.PositiveIntegerField(default=15)),
                ('priority', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Residents',
                'constraints': [models.CheckConstraint(condition=models.Q(('capacity__lte', 20)), name='capacity_not_exceed_20')],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('resident', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='rooms.resident')),
                ('Room', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
            options={
                'verbose_name_plural': 'Allocations',
            },
        ),
    ]
