# Generated by Django 5.1 on 2024-08-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='address',
            field=models.CharField(choices=[('p1', 'Zone 1'), ('p2', 'Zone 2'), ('p3', 'Zone 3'), ('p4', 'Zone 4'), ('p5', 'Zone 5'), ('p6', 'Zone 6'), ('p7', 'Zone 7'), ('p8', 'Zone 8')], default='Zone 1', max_length=55),
        ),
    ]
