# Generated by Django 5.1 on 2024-08-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_resident_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='Room',
            new_name='room',
        ),
    ]
