# Generated by Django 5.1 on 2024-09-11 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_rename_room_allocation_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='name',
        ),
        migrations.AddField(
            model_name='resident',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='resident',
            name='fname',
            field=models.CharField(default='Add First Name', max_length=75),
        ),
        migrations.AddField(
            model_name='resident',
            name='lname',
            field=models.CharField(default='Add Last Name', max_length=75),
        ),
        migrations.AddField(
            model_name='resident',
            name='priority_category',
            field=models.CharField(choices=[('SC', 'Senior Citizen'), ('PWD', 'Person with Disability'), ('P', 'Pregnant'), ('SC & PWD', 'Senior Citizen and PWD'), ('SC & P', 'Senior Citizen and Pregnant'), ('PWD & P', 'PWD and Pregnant'), ('ALL', 'Senior Citizen, PWD, and Pregnant'), ('NONE', 'None')], default='None', max_length=55),
        ),
        migrations.AddField(
            model_name='resident',
            name='priority_members',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
