# Generated by Django 5.1 on 2024-10-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_remove_resident_name_resident_date_resident_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='street',
            field=models.CharField(default='Gil Malungkot Street', max_length=75),
        ),
        migrations.AlterField(
            model_name='resident',
            name='priority_category',
            field=models.CharField(choices=[('SC', 'Senior Citizen'), ('PWD', 'Person with Disability'), ('P', 'Pregnant'), ('SC & PWD', 'Senior Citizen and PWD'), ('SC & P', 'Senior Citizen and Pregnant'), ('PWD & P', 'PWD and Pregnant'), ('ALL', 'Senior Citizen, PWD, and Pregnant'), ('NONE', 'None')], default='NONE', max_length=55),
        ),
    ]
